package main

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cloudapp3/vmbench/checkup"
	"github.com/cloudapp3/vmbench/sysinfo"
)

// shareCheckupPath writes a checkup fixture carrying public identity
// addresses and a hostname, the fields share redaction must handle.
func shareCheckupPath(t *testing.T) string {
	t.Helper()
	rep := checkup.CheckupReport{
		ReportKind: "checkup",
		System: sysinfo.SystemInfo{OS: sysinfo.OSInfo{
			Hostname: "prod-web-01", Name: "Ubuntu 24.04", Kernel: "6.8.0",
		}},
		NetworkInfo: checkup.NetworkInfoSection{
			SectionState: checkup.SectionState{Enabled: true, Status: "ok"},
			Result: &checkup.NetworkIdentityResult{
				PublicIPv4: &checkup.PublicIPIdentity{IP: "96.9.228.37", IPVersion: "v4"},
			},
		},
	}
	data, err := json.Marshal(rep)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "checkup.json")
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestUsageRowsIncludeShare(t *testing.T) {
	joined := strings.Join(usageRows(), "\n")
	if !strings.Contains(joined, "vmbench share") {
		t.Fatalf("usage rows lack share command:\n%s", joined)
	}
}

func TestRunShareArgumentValidation(t *testing.T) {
	path := shareCheckupPath(t)
	notAReport := filepath.Join(t.TempDir(), "other.json")
	if err := os.WriteFile(notAReport, []byte(`{"hello":"world"}`), 0o600); err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		name string
		args []string
	}{
		{name: "no report", args: []string{"share"}},
		{name: "two reports", args: []string{"share", path, path}},
		{name: "unknown format", args: []string{"share", "--format", "yaml", path}},
		{name: "unknown media", args: []string{"share", "--media", "verbose", path}},
		{name: "unknown redact", args: []string{"share", "--redact", "aggressive", path}},
		{name: "unknown provider", args: []string{"share", "--provider", "bogus", path}},
		{name: "custom without endpoint", args: []string{"share", "--provider", "custom", path}},
		{name: "not a report", args: []string{"share", notAReport}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if code := run(tt.args); code != 2 {
				t.Fatalf("share %v exit = %d, want 2", tt.args, code)
			}
		})
	}
}

func TestRunShareMissingFileExitsOne(t *testing.T) {
	if code := run([]string{"share", filepath.Join(t.TempDir(), "absent.json")}); code != 1 {
		t.Fatalf("share with missing file exit = %d, want 1", code)
	}
}

func TestRunShareDryRunTouchesNoNetwork(t *testing.T) {
	var hits int
	srv := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		hits++
	}))
	defer srv.Close()
	path := shareCheckupPath(t)

	output, code := captureStdout(t, func() int {
		return run([]string{"share", "--dry-run", "--provider", "custom", "--share-endpoint", srv.URL, path})
	})
	if code != 0 {
		t.Fatalf("share --dry-run exit = %d", code)
	}
	if hits != 0 {
		t.Fatalf("dry-run performed %d network requests, want 0", hits)
	}
	if !strings.Contains(output, "203.0.113.1") {
		t.Fatalf("dry-run payload lacks the placeholder address:\n%s", output)
	}
	if strings.Contains(output, "96.9.228.37") {
		t.Fatalf("dry-run payload leaked the public address:\n%s", output)
	}
	if !strings.Contains(output, "generated by") {
		t.Fatalf("dry-run payload lacks the footer:\n%s", output)
	}
}

func TestRunShareRedactNoneWarns(t *testing.T) {
	path := shareCheckupPath(t)
	stderr, code := captureStderr(t, func() int {
		return run([]string{"share", "--dry-run", "--redact", "none", path})
	})
	if code != 0 {
		t.Fatalf("share --redact none --dry-run exit = %d", code)
	}
	if !strings.Contains(stderr, "keeps real public IPs") {
		t.Fatalf("missing redaction-disabled warning:\n%s", stderr)
	}
}

func TestRunShareReadsStdinDash(t *testing.T) {
	path := shareCheckupPath(t)
	file, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()
	original := os.Stdin
	os.Stdin = file
	code := run([]string{"share", "--dry-run", "-"})
	os.Stdin = original
	if code != 0 {
		t.Fatalf("share - exit = %d, want 0", code)
	}
}

func TestRunShareCustomUploadEndToEnd(t *testing.T) {
	var uploaded string
	srv := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		uploaded = string(body)
		io.WriteString(w, "https://example.com/shared/1\n")
	}))
	defer srv.Close()
	originalClient := shareUploadClient
	shareUploadClient = srv.Client()
	t.Cleanup(func() { shareUploadClient = originalClient })
	path := shareCheckupPath(t)
	payloadPath := filepath.Join(t.TempDir(), "payload.md")

	output, code := captureStdout(t, func() int {
		return run([]string{"share",
			"--provider", "custom", "--share-endpoint", srv.URL,
			"--save-payload", payloadPath,
			path,
		})
	})
	if code != 0 {
		t.Fatalf("share custom upload exit = %d", code)
	}
	if !strings.Contains(output, "https://example.com/shared/1") {
		t.Fatalf("stdout lacks the paste URL:\n%s", output)
	}
	if !strings.Contains(uploaded, "203.0.113.1") || strings.Contains(uploaded, "96.9.228.37") {
		t.Fatalf("uploaded payload redaction wrong:\n%s", uploaded)
	}
	if !strings.Contains(uploaded, "generated by") {
		t.Fatalf("uploaded payload lacks the footer:\n%s", uploaded)
	}

	saved, err := os.ReadFile(payloadPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(saved) != uploaded {
		t.Fatalf("--save-payload file differs from the uploaded bytes")
	}
	info, err := os.Stat(payloadPath)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0o600 {
		t.Fatalf("payload file mode = %o, want 600", got)
	}
}
